---
language: python
cache: pip
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - ansible-playbook -i hosts test.yml --syntax-check
  - ansible-playbook -i hosts test.yml
  - ansible-playbook -i hosts test.yml | grep -q 'changed=0.*failed=0'
