---
- name: Install latest versions of packages.
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - git
    - curl
  become: true
  when: ansible_os_family == "Debian" and exec_mode == "vm"
- name: Remove dependencies that are no longer required.
  apt:
    autoremove: "yes"
  when: ansible_os_family == "Debian" and exec_mode == "vm"
