---
- name: Adding vagrant user to docker group.
  user:
    name: vagrant
    group: vagrant
    groups: docker
    append: "yes"
  become: true
  when: ansible_os_family == "Debian" and exec_mode == "vm"
- name: Restart docker systemd unit.
  systemd:
    name: docker
    state: restarted
    daemon_reload: "yes"
  become: true
  when: ansible_os_family == "Debian" and exec_mode == "vm"
